# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Unjugador.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1135, 741)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(600, 530, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 500, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.progressBarFeliz = QtWidgets.QProgressBar(Form)
        self.progressBarFeliz.setGeometry(QtCore.QRect(160, 540, 291, 21))
        self.progressBarFeliz.setProperty("value", 0)
        self.progressBarFeliz.setObjectName("progressBarFeliz")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(40, 630, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(40, 540, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lcdNumberPuntuacion = QtWidgets.QLCDNumber(Form)
        self.lcdNumberPuntuacion.setGeometry(QtCore.QRect(700, 600, 81, 41))
        self.lcdNumberPuntuacion.setObjectName("lcdNumberPuntuacion")
        self.progressBarTriste = QtWidgets.QProgressBar(Form)
        self.progressBarTriste.setGeometry(QtCore.QRect(160, 600, 291, 23))
        self.progressBarTriste.setProperty("value", 0)
        self.progressBarTriste.setObjectName("progressBarTriste")
        self.labelEmoji = QtWidgets.QLabel(Form)
        self.labelEmoji.setGeometry(QtCore.QRect(630, 20, 361, 371))
        self.labelEmoji.setText("")
        self.labelEmoji.setPixmap(QtGui.QPixmap("61ed5f7254a19746b1ef35e0c3d35e46.png"))
        self.labelEmoji.setScaledContents(True)
        self.labelEmoji.setObjectName("labelEmoji")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(40, 600, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(790, 390, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(40, 660, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.progressBarEnojado = QtWidgets.QProgressBar(Form)
        self.progressBarEnojado.setGeometry(QtCore.QRect(160, 570, 291, 23))
        self.progressBarEnojado.setProperty("value", 0)
        self.progressBarEnojado.setObjectName("progressBarEnojado")
        self.labelSiguienteEmoji = QtWidgets.QLabel(Form)
        self.labelSiguienteEmoji.setGeometry(QtCore.QRect(1030, 280, 61, 61))
        self.labelSiguienteEmoji.setText("")
        self.labelSiguienteEmoji.setPixmap(QtGui.QPixmap("6d3e39de64dc75c20fe665ca0820afc3.png"))
        self.labelSiguienteEmoji.setScaledContents(True)
        self.labelSiguienteEmoji.setObjectName("labelSiguienteEmoji")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(1020, 360, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(40, 570, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lcdNumberCombo = QtWidgets.QLCDNumber(Form)
        self.lcdNumberCombo.setGeometry(QtCore.QRect(700, 530, 81, 41))
        self.lcdNumberCombo.setObjectName("lcdNumberCombo")
        self.progressBarSorp = QtWidgets.QProgressBar(Form)
        self.progressBarSorp.setGeometry(QtCore.QRect(160, 630, 291, 23))
        self.progressBarSorp.setProperty("value", 0)
        self.progressBarSorp.setObjectName("progressBarSorp")
        self.labelFoto = QtWidgets.QLabel(Form)
        self.labelFoto.setGeometry(QtCore.QRect(20, 20, 591, 441))
        self.labelFoto.setText("")
        self.labelFoto.setPixmap(QtGui.QPixmap("Gritos.PNG"))
        self.labelFoto.setScaledContents(True)
        self.labelFoto.setObjectName("labelFoto")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(570, 600, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.progressBarNormal = QtWidgets.QProgressBar(Form)
        self.progressBarNormal.setGeometry(QtCore.QRect(160, 660, 291, 23))
        self.progressBarNormal.setProperty("value", 0)
        self.progressBarNormal.setObjectName("progressBarNormal")
        self.pushButtonResultados = QtWidgets.QPushButton(Form)
        self.pushButtonResultados.setGeometry(QtCore.QRect(910, 600, 111, 41))
        self.pushButtonResultados.setObjectName("pushButtonResultados")
        self.pushButtonIniciar = QtWidgets.QPushButton(Form)
        self.pushButtonIniciar.setGeometry(QtCore.QRect(910, 530, 111, 41))
        self.pushButtonIniciar.setObjectName("pushButtonIniciar")
        self.labelContador = QtWidgets.QLabel(Form)
        self.labelContador.setGeometry(QtCore.QRect(740, 410, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelContador.setFont(font)
        self.labelContador.setText("")
        self.labelContador.setObjectName("labelContador")
        self.label.setPixmap(QtGui.QPixmap(".images/Gen 1900x1000.png"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Combo:"))
        self.label_2.setText(_translate("Form", "Porcentajes:"))
        self.label_11.setText(_translate("Form", "Sorprendido:"))
        self.label_6.setText(_translate("Form", "Feliz:"))
        self.label_10.setText(_translate("Form", "Triste:"))
        self.label_4.setText(_translate("Form", "Emoji"))
        self.label_12.setText(_translate("Form", "Normal:"))
        self.label_13.setText(_translate("Form", "Siguiente"))
        self.label_9.setText(_translate("Form", "Enojado:"))
        self.label_8.setText(_translate("Form", "Puntuacion:"))
        self.pushButtonResultados.setText(_translate("Form", "Resultados"))
        self.pushButtonIniciar.setText(_translate("Form", "Iniciar"))
        
