# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UnJugador1900x1000.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1898, 1000)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(960, 670, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 570, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.progressBarFeliz = QtWidgets.QProgressBar(Form)
        self.progressBarFeliz.setGeometry(QtCore.QRect(220, 620, 641, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.progressBarFeliz.setFont(font)
        self.progressBarFeliz.setProperty("value", 80)
        self.progressBarFeliz.setObjectName("progressBarFeliz")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(50, 750, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(50, 620, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lcdNumberPuntuacion = QtWidgets.QLCDNumber(Form)
        self.lcdNumberPuntuacion.setGeometry(QtCore.QRect(1120, 770, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumberPuntuacion.setFont(font)
        self.lcdNumberPuntuacion.setProperty("intValue", 0)
        self.lcdNumberPuntuacion.setObjectName("lcdNumberPuntuacion")
        self.progressBarTriste = QtWidgets.QProgressBar(Form)
        self.progressBarTriste.setGeometry(QtCore.QRect(220, 710, 641, 23))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.progressBarTriste.setFont(font)
        self.progressBarTriste.setProperty("value", 24)
        self.progressBarTriste.setObjectName("progressBarTriste")
        self.labelEmoji = QtWidgets.QLabel(Form)
        self.labelEmoji.setGeometry(QtCore.QRect(1010, 10, 501, 501))
        self.labelEmoji.setText("")
        self.labelEmoji.setPixmap(QtGui.QPixmap("feliz.png"))
        self.labelEmoji.setScaledContents(True)
        self.labelEmoji.setObjectName("labelEmoji")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(50, 710, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(1240, 510, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(50, 790, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.progressBarEnojado = QtWidgets.QProgressBar(Form)
        self.progressBarEnojado.setGeometry(QtCore.QRect(220, 660, 641, 23))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.progressBarEnojado.setFont(font)
        self.progressBarEnojado.setProperty("value", 24)
        self.progressBarEnojado.setObjectName("progressBarEnojado")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(50, 660, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lcdNumberCombo = QtWidgets.QLCDNumber(Form)
        self.lcdNumberCombo.setGeometry(QtCore.QRect(1120, 670, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumberCombo.setFont(font)
        self.lcdNumberCombo.setObjectName("lcdNumberCombo")
        self.progressBarSorp = QtWidgets.QProgressBar(Form)
        self.progressBarSorp.setGeometry(QtCore.QRect(220, 750, 641, 23))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.progressBarSorp.setFont(font)
        self.progressBarSorp.setProperty("value", 24)
        self.progressBarSorp.setObjectName("progressBarSorp")
        self.labelFoto = QtWidgets.QLabel(Form)
        self.labelFoto.setGeometry(QtCore.QRect(60, 20, 781, 541))
        self.labelFoto.setText("")
        self.labelFoto.setPixmap(QtGui.QPixmap("Gritos.PNG"))
        self.labelFoto.setScaledContents(True)
        self.labelFoto.setObjectName("labelFoto")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(960, 770, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.progressBarNormal = QtWidgets.QProgressBar(Form)
        self.progressBarNormal.setGeometry(QtCore.QRect(220, 790, 641, 23))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.progressBarNormal.setFont(font)
        self.progressBarNormal.setProperty("value", 24)
        self.progressBarNormal.setObjectName("progressBarNormal")
        self.pushButtonResultados = QtWidgets.QPushButton(Form)
        self.pushButtonResultados.setGeometry(QtCore.QRect(1500, 640, 181, 161))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButtonResultados.setFont(font)
        self.pushButtonResultados.setStyleSheet(" QPushButton {\n"
"    color: brown;          \n"
"    border-image: url(/Users/Juan/Desktop/Interfaces Guapometro/results.png) 3 10 3 10;\n"
" }")
        self.pushButtonResultados.setText("")
        self.pushButtonResultados.setObjectName("pushButtonResultados")
        self.pushButtonIniciar = QtWidgets.QPushButton(Form)
        self.pushButtonIniciar.setGeometry(QtCore.QRect(1310, 640, 191, 181))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonIniciar.setFont(font)
        self.pushButtonIniciar.setStyleSheet(" QPushButton {\n"
"            color: brown;\n"
"            border-image: url(/Users/Juan/Desktop/Interfaces Guapometro/play.png) 3 10 3 10;\n"
"\n"
"        }")
        self.pushButtonIniciar.setText("")
        self.pushButtonIniciar.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonIniciar.setObjectName("pushButtonIniciar")
        self.labelContador = QtWidgets.QLabel(Form)
        self.labelContador.setEnabled(True)
        self.labelContador.setGeometry(QtCore.QRect(1220, 540, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelContador.setFont(font)
        self.labelContador.setText("")
        self.labelContador.setObjectName("labelContador")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1900, 1000))
        self.label.setMouseTracking(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/Gen 1900x1000.png"))
        self.label.setObjectName("label")
        self.labelSiguienteEmoji_2 = QtWidgets.QLabel(Form)
        self.labelSiguienteEmoji_2.setGeometry(QtCore.QRect(1690, 360, 101, 101))
        self.labelSiguienteEmoji_2.setText("")
        self.labelSiguienteEmoji_2.setPixmap(QtGui.QPixmap("6d3e39de64dc75c20fe665ca0820afc3.png"))
        self.labelSiguienteEmoji_2.setScaledContents(True)
        self.labelSiguienteEmoji_2.setObjectName("labelSiguienteEmoji_2")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(1700, 480, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.pushButtonReset = QtWidgets.QPushButton(Form)
        self.pushButtonReset.setGeometry(QtCore.QRect(1690, 650, 161, 151))
        self.pushButtonReset.setStyleSheet(" QPushButton {\n"
"    color: brown;\n"
"    border-image: url(/Users/Juan/Desktop/Interfaces Guapometro/reset.png) 3 10 3 10;\n"
" }")
        self.pushButtonReset.setText("")
        self.pushButtonReset.setObjectName("pushButtonReset")
        self.label.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.progressBarFeliz.raise_()
        self.label_11.raise_()
        self.label_6.raise_()
        self.lcdNumberPuntuacion.raise_()
        self.progressBarTriste.raise_()
        self.labelEmoji.raise_()
        self.label_10.raise_()
        self.label_4.raise_()
        self.label_12.raise_()
        self.progressBarEnojado.raise_()
        self.label_9.raise_()
        self.lcdNumberCombo.raise_()
        self.progressBarSorp.raise_()
        self.labelFoto.raise_()
        self.label_8.raise_()
        self.progressBarNormal.raise_()
        self.pushButtonResultados.raise_()
        self.pushButtonIniciar.raise_()
        self.labelContador.raise_()
        self.labelSiguienteEmoji_2.raise_()
        self.label_14.raise_()
        self.pushButtonReset.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Combo:"))
        self.label_2.setText(_translate("Form", "Porcentajes:"))
        self.label_11.setText(_translate("Form", "Sorprendido:"))
        self.label_6.setText(_translate("Form", "Feliz:"))
        self.label_10.setText(_translate("Form", "Triste:"))
        self.label_4.setText(_translate("Form", "Emoji"))
        self.label_12.setText(_translate("Form", "Normal:"))
        self.label_9.setText(_translate("Form", "Enojado:"))
        self.label_8.setText(_translate("Form", "Puntuacion:"))
        self.label_14.setText(_translate("Form", "Siguiente"))

